services:
  - type: web
    name: car-price-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn advanced.submissions.team_members.Rajat.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0